config/routes.rb
Rails.application.routes.draw do
  get 'user/summary' => 'summary#index'
  get 'favorites/update'
  devise_for :users
  resources :restaurants do
    resources :comments, only: [:create]
  end
  resources :users
  resources :restaurant
  resources :votes, only:[:create, :destroy]
  root 'restaurants#index'

  put '/restaurants/:id/yes', to: 'restaurants#yes', as: 'yes'
  put '/restaurants/:id/no', to: 'restaurants#no', as: 'no'

  get 'searchName', to: "restaurants#index"
  get 'searchLocation', to: "restaurants#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :votes
  has_many :comments
  has_many :favorites
  after_initialize :set_defaults, unless: :persisted?
  validates :name, presence: true
  validates :website, allow_blank: true, format: {
    with:     %r{\.(com|net|couk|edu)\z}i,
    message: 'Must be a valid website.'
  }
  validates :location, presence: true,
  format: {
    with: /\A[a-zA-Z\s]+,\s[a-zA-Z]{2}\z/,
    message: "Location must be City, ST"
  }

  validates :yes_split, :no_split, numericality: {
    greater_than_or_equal_to: 0
  }

  def set_defaults
    self.yes_split ||= 0
    self.no_split ||= 0
  end

  def yes
    self.yes_split += 1
    self.save
  end

  def no
    self.no_split += 1
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :votes
  has_many :comments
  has_many :favorites
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  def yes
    self.vote_type = "Yes"
    self.save
  end

  def no
    self.vote_type = "No"
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def favorite_text
    return @favorite_exists ? "Unfavorite" : "Favorite"
  end

  helper_method :favorite_text
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.new(comment_params)
    if !@comment.save
      flash[:notice] = @comment.errors.full_messages.to_sentence
    end
    redirect_to restaurant_path(params[:restaurant_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(restaurant_id: params[:restaurant_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def update
    @restaurant = Restaurant.find(params[:restaurant])
    favorite = Favorite.where(restaurant: Restaurant.find(params[:restaurant]), user: current_user)
    if favorite == []
      Favorite.create(restaurant: Restaurant.find(params[:restaurant]), user: current_user)
      @favorite_exists = true
    else
      favorite.destroy_all
      @favorite_exists = false
  end
  redirect_to restaurant_path(@restaurant)
end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]
  

  # GET /restaurants or /restaurants.json
  def index
    if !params[:n].nil? && !params[:n].empty?
     @restaurants = Restaurant.where("name LIKE ?", "%" + params[:n] +"%")
    else if !params[:s].nil? && !params[:s].empty?
      @restaurants = Restaurant.where("location LIKE ?", "%" + params[:s] +"%")
    end
  end
end


  # GET /restaurants/1 or /restaurants/1.json
  def show
    @restaurant = Restaurant.all.find(params[:id])
    @favorite_exists = Favorite.where(restaurant: @restaurant, user: current_user) == [] ? false : true

  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

def yes
 @restaurant = Restaurant.all.find(params[:id])
 @restaurant.yes

 redirect_to restaurant_path(@restaurant)
end

def no
 @restaurant = Restaurant.all.find(params[:id])
 @restaurant.no
 redirect_to restaurant_path(@restaurant)
end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :website, :yes_split, :no_split)
    end

end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def index
    @user = current_user
    end
  end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
before_action :authenticate_user!

    def create
      @vote = current_user.votes.new(vote_params)
      if !@vote.save
      flash[:notice] = @vote.errors.full_messages.to_sentence
      end
    redirect_to @vote.restaurant
  end

  private
  def vote_params
    params.require(:vote).permit(:restaurant_id, :vote_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<article>

  <p><%= comment.content %></p>
  <small>
    by <%= comment.user.email %></small>
  </article>
<hr /r>

app/views/comments/_form.html.erb
<form action="<%= restaurant_comments_path(restaurant) %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<textarea name="comment[content]" id=" rows="8" cols="30"></textarea>

  <input type="submit" value="Submit">
  </form>

app/views/favorites/update.js.erb
$('favorite_link').text("<%= favorite_text %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Split The Check</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render "/layouts/shared/header" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<div class="row justify-content-center">
<div class="col-7 align-self-center">
<div class="login-links">
<% if user_signed_in? then %>
Hello, <%=  current_user.email %><br>
<%= link_to 'User Summary', user_summary_path %><br>
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<% else %>

<%= link_to 'Login', new_user_session_path %><br><%= link_to 'Register', new_user_registration_path %>
</div>
<% end %>
<div class="header">
<h1>Split the Check!</h1>
</div>
<% if notice then %>
<p class="alert alert-success"><%= notice %></p>
<% end  %>
<% if alert then %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>
</div>
</div>

app/views/restaurants/_form.html.erb
<div class="form">
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Restaurant Name:<br>
    <%= form.text_field :name, id: "name" %>
  </div>

  <div class="field">
    Restaurant Location:<br>
    <%= form.text_field :location, id: "location"%>
  </div>

  <div class="field"><br>
    Restaurant Website (Optional):<br>
    <%= form.text_field :website, id:"website" %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/restaurants/_header.html.erb
<div class="row justify-content-center">
<div class="col-7 align-self-center">

<% if user_signed_in? then %>
Hello, <%= current_user.email %>
<% else %>
<div class="login">
<%= link_to 'Login', new_user_session_path %><br><%= link_to 'Register', new_user_registration_path %>
</div>
<% end %>
<div class="header">
<h1>Split the Check!</h1>
</div>
</div>
</div>

app/views/restaurants/_searchResults.html.erb
<% if !@restaurants.nil? %>
<h1>Search Results</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>

      <th colspan="3"></th>
    </tr>
  </thead>

<% @restaurants.each do |restaurant| %>
   <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= restaurant.name %></td>
    <td><%= restaurant.location %></td>
    <td><%= link_to 'Show', restaurant %></td>
  </tr>
<% end %>
<% end %>
</table>

app/views/restaurants/edit.html.erb
<div class="container">
  
<h1>Edit</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<div class="container">

  <div class="row justify-content-center">
    <h1>Search</h1>
    <div class="searchBoxes">
    <div class="col">

    Name:
    <form class="form" action="/searchName">
    <input class="form-control-inline" name="n" id="name"  type="text" placeholder="Name" aria-label="Search">
    <button class="btn btn-outline-success" type="submit" id="searchname">Search</button>

    </form>
    </div>
    <br>
    <div class="row">
    <div class="col">

    Location:
    <form class="form" action="/searchLocation">
    <input class="form-control-inline" name="s" id="location" type="text" placeholder="Location" aria-label="Search">
    <button class="btn btn-outline-success" type="submit" id="searchlocation">Search</button>
    </form>
    </div>
    </div>
    <% if user_signed_in? then %>
  <%= link_to 'Add Restaurant', new_restaurant_path %>
  <% end %>
    </div>

  <br>
</div>
<div class="row">

<% if @restaurants.present? %>
<%= render "searchResults" %>
<% end %>

<p></p>
</div>
</div>

app/views/restaurants/new.html.erb
<div class="container">

<h1>Add Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
<div class="showRestaurantInfo">
    <div class="col align-self-center">
    <div class="row justify-content-center">
<div class="showName">
 <h1><%= @restaurant.name %></h1>
 </div>
</div>
</div>
<div class="row justify-content-center">
  <div class="showLocation">
  <%= @restaurant.location %>
  </div>
  </div>

  <div class="row justify-content-center">
    <div class="showWebsite">
<% if @restaurant.website? then %>
  <%= link_to "Restaurant Website", @restaurant.website, :target=> '_blank' %>
  <% end %>
  <br>
  <% if user_signed_in? then %>
  <%= link_to "Edit", edit_restaurant_path(@restaurant) %>
  <br><br>
  <% if @favorite_exists then %>
  <%= link_to "Unfavorite", favorites_update_path(restaurant: @restaurant) %>
<% else %>
<%= link_to "Favorite", favorites_update_path(restaurant: @restaurant) %>
<% end %>
  <% end %>

  </div>
  </div>
  </div>

  <div class="row justify-content-center">


      <div class="col-6">
  <div class="showPercent">
    <% if (@restaurant.votes.all.count == 0) %>
      Not Enough Votes!
      <% elsif (@restaurant.votes.where(vote_type:"Yes").count > 0 && @restaurant.votes.where(vote_type:"No").count == 0) %>
      100% Yes
      <% elsif (@restaurant.votes.where(vote_type:"Yes").count == 0 && @restaurant.votes.where(vote_type:"No").count > 0) %>
      0% Yes
      <% else %>
        <%= ((@restaurant.votes.where(vote_type:"Yes").count.to_f / @restaurant.votes.all.count) * 100).to_i %> % Yes

<% end %>

</div>
</div>
</div>

  <div class="row justify-content-center">
<div class="showVoteAmount">

Yes Votes: <%= @restaurant.votes.where(vote_type:"Yes").count %>

No Votes: <%= @restaurant.votes.where(vote_type:"No").count %>

All Votes <%= @restaurant.votes.count %>
</div>
</div>
  <% if user_signed_in? then %>
<div class="row justify-content-center">
  <div class="col-6">
<div class="showVoteButtons">
  Did <%= @restaurant.name %> split the check for you?
<div class="row justify-content-center">
<div class="col-6">
  <br>
  <form action="/votes" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="vote[restaurant_id]" value="<%= @restaurant.id %>">
        <input type="hidden" name="vote[vote_type]" value="Yes">
    <input type="submit" value="Yes" class="btn btn-primary">
    </form>
    <form action="/votes" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="vote[restaurant_id]" value="<%= @restaurant.id %>">
        <input type="hidden" name="vote[vote_type]" value="No">
      <input type="submit" value="No" class="btn btn-danger">
      </form>
<% else %>
<div class="row justify-content-center">
  <div class="col-5">
    <div class="showVoteButtons">
Please <%= link_to 'log in', new_user_session_path %> or <%= link_to 'sign up', new_user_registration_path %> to cast your vote!
</div>
</div>

<% end %>
</div>
</div>
  </div>
<br><br>
    <p>
<div class="comments">
    <strong>Comments: </strong>
    <%= render @restaurant.comments %>
    <br>
      <% if user_signed_in? then %>
    <%= render partial: 'comments/form', locals: { restaurant: @restaurant } %>
    <% else %>
    <%= link_to 'Log in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %> to leave a comment!
    <% end %>
    </p>
</div>


    </div>



</div>
</div>




<%= link_to 'Back', restaurants_path %>
</div>

app/views/summary/_comments.html.erb
<% @user.comments.each do |comment| %>

<%= comment.content %>
<small><%= link_to comment.restaurant.name, comment.restaurant %> at <%= comment.created_at %></small>

<br>
<hr /r>
<% end %>
<br>

app/views/summary/_favorites.html.erb
<% @user.favorites.each do |favorite| %>
<%= link_to favorite.restaurant.name, favorite.restaurant %>
<br>

<% end %>

app/views/summary/_votes.html.erb
<table>
  <thead>
    <tr>
      <th>Restaurant</th>
      <th>Vote</th>

      <th colspan="3"></th>
    </tr>
  </thead>

<% @user.votes.each do |vote| %>
   <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= vote.restaurant.name %></td>
    <td><%= vote.vote_type %></td>
    <td><%= link_to 'Show', vote.restaurant %></td>
  </tr>
<% end %>
</table>

app/views/summary/index.html.erb
<div class="container"><div class="showHistory">
  <h1>User Summary</h1>
  <div class="col-md">
<div class="row">

<h2>Votes:</h2>
<% if @user.votes.count > 0 then %>
<%= render partial: 'summary/votes' %>
<% else %>
<br>
You have no votes.
<% end %>
</div>
<br><br><br>
<div class="row">

  <h2>Favorites:</h2>
<% if @user.favorites.count > 0 then %>
<%= render partial: 'summary/favorites' %>
<% else %>
<br>
You have no favorites.
<% end %>
</div>
<br><br><br>
<div class="row">

    <br>
    <br>
<h2>Comments:</h2>
<% if @user.comments.count > 0 then %>
<%= render partial: 'summary/comments' %>
<% else %>
<br>
You have made no comments.
<% end %>
</div>
</div>
<br><br>
<%= link_to 'Home', restaurants_path %>
</div>
</div>